languageCode = "en-us"
title = "Geoffrey -> Blog"
author = "gcline"
theme = "gcactus"

summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Public"
url = "/public"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
    description = "Geoffrey is a general-purpose website user."
    mainSection = "posts"
    showAllPostsOnHomePage = true
    dateFormat = "02Jan2006"

    [[params.social]]
    name = "github"
    link = "https://github.com/geoffcline"

    [[params.social]]
    name = "email"
    link = "geoffreyc@outlook.com"

    [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/geoffrey-cline/"

    [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/geoff_cline/"